[package]
name = "kirin-derive"
version = "0.1.0"
edition = "2024"

[dependencies]
kirin-derive-core = { version = "0.1.0", path = "../kirin-derive-core" }
proc-macro2 = "1.0.103"
quote = "1.0.42"
syn = "2.0.109"

[lib]
proc-macro = true
