[package]
name = "kirin-constant"
version = "0.1.0"
edition = "2024"

[dependencies]
kirin.workspace = true
kirin-interpreter = { workspace = true, optional = true }

[features]
interpret = ["kirin-interpreter"]
