[package]
name = "kirin-derive-dialect"
version = "0.1.0"
edition = "2024"

[dependencies]
kirin-derive-core-2 = { version = "0.1.0", path = "../kirin-derive-core-2" }
proc-macro2 = "1.0.105"
quote = "1.0.43"
