[package]
name = "kirin-chumsky-2"
version = "0.1.0"
edition = "2024"

[dependencies]
ariadne = "0.6.0"
chumsky = "0.12.0"
kirin-ir = { version = "0.1.0", path = "../kirin-ir" }
kirin-lexer = { version = "0.1.0", path = "../kirin-lexer" }

[dev-dependencies]
insta = "1.45.0"
