[package]
name = "kirin-bitwise"
version = "0.1.0"
edition = "2024"

[dependencies]
kirin.workspace = true

[dev-dependencies]
kirin-arith.workspace = true
kirin-cf.workspace = true
kirin-constant.workspace = true
