[package]
name = "kirin-derive-core"
version = "0.1.0"
edition = "2024"

[dependencies]
either = "1.15.0"
eyre = "0.6.12"
proc-macro2 = "1.0.103"
quote = "1.0.42"
syn = "2.0.109"

[dev-dependencies]
insta = "1.43.2"
