[package]
name = "kirin-lexer"
version = "0.1.0"
edition = "2024"

[dependencies]
logos.workspace = true
proc-macro2 = { workspace = true, optional = true }
quote = { workspace = true, optional = true }

[features]
quote = ["dep:quote", "dep:proc-macro2"]
