[package]
name = "kirin-function"
version = "0.1.0"
edition = "2024"

[dependencies]
kirin = { version = "0.1.0", path = "../.." }
kirin-test-utils = { workspace = true, features = ["parser", "pretty"] }
