[package]
name = "kirin-test-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
kirin-ir = { version = "0.1.0", path = "../kirin-ir", default-features = false }
kirin-chumsky = { workspace = true, optional = true }
kirin-lexer = { workspace = true, optional = true }
kirin-prettyless = { workspace = true, optional = true }
kirin-interpreter = { workspace = true, optional = true }
kirin-arith = { workspace = true, optional = true, features = ["interpret"] }
kirin-cf = { workspace = true, optional = true, features = ["interpret"] }
kirin-constant = { workspace = true, optional = true, features = ["interpret"] }
kirin-function = { workspace = true, optional = true, features = ["interpret"] }
kirin-derive = { workspace = true, optional = true }
kirin-derive-interpreter = { workspace = true, optional = true }

[features]
default = []
simple-language = ["kirin-ir/derive"]
parser = ["kirin-chumsky", "kirin-lexer"]
pretty = ["kirin-prettyless"]
roundtrip = ["parser", "pretty"]
interpreter = ["kirin-interpreter", "kirin-arith", "kirin-cf", "kirin-constant", "kirin-function", "kirin-derive", "kirin-derive-interpreter", "kirin-ir/derive", "pretty"]
