[package]
name = "kirin-test-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
kirin-ir = { version = "0.1.0", path = "../kirin-ir", default-features = false }
kirin-chumsky = { workspace = true, optional = true }
kirin-lexer = { workspace = true, optional = true }
kirin-prettyless = { workspace = true, optional = true }
kirin-test-languages = { workspace = true, optional = true }

[features]
default = []
parser = ["kirin-chumsky", "kirin-lexer"]
pretty = ["kirin-prettyless"]
roundtrip = ["parser", "pretty"]
interpreter = ["kirin-test-languages/composite-language", "kirin-test-languages/pretty", "pretty", "dep:kirin-test-languages"]
